### ISSUE TITLE
Geologic Names Check tool warns you are using an obsolete tool, version 2.12.13

### ISSUE THREAD

**Issue by LLeBlanc110** [DOI-USGS/gems-tools-pro#103]
![image](https://github.com/DOI-USGS/gems-tools-pro/assets/61474179/0f98ad3e-c76c-4db2-ad53-794020008884)

I have an older version of the toolbox added to my project (that I can't seem to get rid of), so it could be potentially pulling from that one?

**Comment by ethoms-usgs** [comment]
Thank you for pointing this out! The tool had the wrong url to look for the most current version. 

But you are up-to-date (1/10/24) so you can ignore the warning and the corrected url will be in the next release.
