### ISSUE TITLE
rawURL typo in GeoLexCheck

### ISSUE THREAD

**Issue by chhalsted** [DOI-USGS/gems-tools-pro#104]
There is an extra forward slash in the rawurl string (..DO/I..) that is causing the checkVersion to always report the tool as not current.
rawurl = "https://raw.githubusercontent.com/DO/I-USGS/gems-tools-pro/master/Scripts/GeMS_GeolexCheck.py"

**Comment by ethoms-usgs** [comment]
Fixed in v2.13
