### ISSUE TITLE
Submission Directory Tree: Entering a space in Map Area string causes silent failure.

### ISSUE THREAD

**Issue by vlatane-va-energy** [DOI-USGS/gems-tools-pro#114]
If the input for Mapped area (or other name) contains a space, the tool will technically succeed, but the output is only the main folder, with the name cut off where the space was in the Mapped area string. I think the space in the string is interrupting gems_mkdir.bat somewhere and the main script has no way of knowing.

Avoiding spaces is implied in the GeMS submittal requirements, but not explicit. It would be nice if the tool flagged the problematic input instead of finishing the run as "Succeeded."

**Comment by ethoms-usgs** [comment]
Fixed in [v2.13.2](https://github.com/DOI-USGS/gems-tools-pro/releases/tag/v2.13.2). The tool will convert spaces to underscores and this is noted in the parameter help/metadata.

**Comment by vlatane-va-energy** [comment]
Thank you!
