### ISSUE TITLE
cross section tool 

### ISSUE THREAD

**Issue by LindaTedrow** [DOI-USGS/gems-tools-pro#123]
The cross section tool (Project Map Data to Cross Section), is not working. 
If I try in ArcMap or ArcPro cannot get it to run.

In ArcMap the error has to do with data not intersecting cross section line; which is technically false.
In ArcPro there seems to be a syntax error.  
  File "<expression>", line 1
    01
    ^
﻿SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
﻿Traceback (most recent call last):
﻿  File "C:\Users\ltedrow\GitHub\gems-tools-pro\Scripts\GeMS_ProjectCrossSectionData.py", line 347, in <module>
﻿    arcpy.CalculateField_management(tempXsLine, idField, "01", "PYTHON3")

I have tried different rasters, different cross section lines, several variations; all to no avail. 

suggestions?

**Comment by ethoms-usgs** [comment]
First, are you using the tool on the [xs-update](https://github.com/DOI-USGS/gems-tools-pro/tree/xs-update) branch?

**Comment by LindaTedrow** [comment]
I do not know; so perhaps not.

**Comment by ethoms-usgs** [comment]
Ok, then you probably aren't. Download the toolbox from that branch and try that version of the tool. Use only that tool there, many of the others are out-of-date on that branch, so keep that copy separate from a copy of the latest release. I have been holding off merging it into the main branch until I hear that it's mostly working for people.

**Comment by ethoms-usgs** [comment]
Great! good to know.
