### ISSUE TITLE
Project Map Data to Cross Section Error for gems-tools-pro-xs-update toolbox

### ISSUE THREAD

**Issue by lawilliams-virginia** [DOI-USGS/gems-tools-pro#25]
Hi USGS folks-

I am trying to use Evan's pro-xs toolbox to use his update to the Cross Section tool. I am getting the following error for the pictured input:  

Traceback (most recent call last):
  File "C:\Users\law1\Documents\GeMS\gems-tools-pro-xs-update\Scripts\GeMS_ProjectCrossSectionData_AGP2.py", line 357, in <module>
    arcpy.AddField_management(copy_xs_line, id_field, 'TEXT')
NameError: name 'copy_xs_line' is not defined

![error1](https://user-images.githubusercontent.com/82409104/176027372-2976b372-507f-4791-95e6-00e7e50217e2.jpg)
![error2](https://user-images.githubusercontent.com/82409104/176027378-64253ab6-2dd9-421d-b5aa-7dc377e8e63a.jpg)

Let me know what I can do to get the tool working. Happy to share the database if need be. We are currently conducting a trial run for doing our cross sections in the GIS environment.

Thanks,
Lauren

**Comment by lawilliams-virginia** [comment]
Apologies for the delay in response. I did get it to work for contacts and faults being projected with an elevation profile. When orientation points are included in feature classes to project, I get the an error (TypeError: 'NoneType' object is not subscriptable). 

![ChesterProfile](https://user-images.githubusercontent.com/82409104/180860790-9d6fa2b3-0cc9-45cc-9e09-43eb9b972675.jpg)
![ChesterFail](https://user-images.githubusercontent.com/82409104/180860797-98ab996a-3440-45fa-9593-1cba4ce20c73.jpg)

**Comment by ethoms-usgs** [comment]
Yup, got the same error. Fixed in the latest push.

**Comment by ethoms-usgs** [comment]
I think is resolved. Will close but we can open it again if needed.

**Comment by ethoms-usgs** [comment]
I think is resolved. Will close but we can open it again if needed.
