### ISSUE TITLE
Translate to Shapefiles throwing an error

### ISSUE THREAD

**Issue by MnashUSGS** [DOI-USGS/gems-tools-pro#29]
![image](https://user-images.githubusercontent.com/99765778/184942654-916efbee-5679-4f53-a599-ee9447d7b855.png)

Attempting to run Translate to Shapefiles tool, and it appears to encounter an error when converting a polygon feature class into a shapefile. 
It appears there is some issue with the variable 'j' being defined, but looking through the code I cannot decipher what else might be the issue. 

This is separate from the other issue regarding different DataSourceIDs - my MapUnitPolys FC all has one DataSourceID.

**Comment by ethoms-usgs** [comment]
Could you send me a list of the field names in that polygon feature class? I just ran the tool with a made-up name that I thought would trigger the same error, but it still completed just fine.

**Comment by ethoms-usgs** [comment]
Closed due to inactivity
