### ISSUE TITLE
NON-UNIQUE VALUE OF LABEL: Silt

### ISSUE THREAD

**Issue by casjone** [DOI-USGS/gems-tools-pro#33]
> NON-UNIQUE VALUE OF LABEL: Silt,
>   Fix it and re-run!

i keep getting this issue when i run the docx to dmu tool. i don't have any labels with the value of "silt"

**Comment by ethoms-usgs** [comment]
Hard to say without looking at the Word doc, but keep in mind that 'label' here (in keeping with USGS publishing legacy) refers to what gets put into the `MapUnit` field in a GeMS dmu, not the `Label` field of that table. 

I haven't dug into the code too deeply, but I bet that isn't expected to be any more than one word or abbreviation; that is, no spaces would be allowed. Are there two entries that are like 'Silt' and 'Silt and sand'?

**Comment by casjone** [comment]
silt doesn't appear in either one of those fields. even when i replace the word 'silt' (which is only found in the description), it returns the same error with whatever i replace the word 'silt' with. i've attached the docx here. 
[testPamphletDmu.docx](https://github.com/usgs/gems-tools-pro/files/9508247/testPamphletDmu.docx)

**Comment by ethoms-usgs** [comment]
Thanks, I will take a look.

**Comment by ethoms-usgs** [comment]
It all comes down to formatting. Each unit needs to have a map unit label, name, age, and description as [below](https://github.com/usgs/gems-tools-pro/wiki/CMU-and-DMU), and all separated by the appropriate spaces, em-dashes, parantheses, and have no paranthetical breaks.

![image](https://user-images.githubusercontent.com/5376315/188977527-af5db1aa-a8a3-4ef8-84dc-aef17a91f31b.png)

testPamphletDmu is closer to working than testPamphletDmu2 (where 'Silt,', because it starts a paragraph, is parsed out as a map unit label) but MARTINSVILLE FORMATION (HOLOCENE) needs to be re-styled as Heading3 and you need to add **(ages)** after all of the unit names. In places where **(undivided)** follows the name instead of, or in addition to, an age, move that to just after the name separated by a comma

![image](https://user-images.githubusercontent.com/5376315/188979128-b566b15d-8499-4178-a8d7-7248a184d636.png)

Try those changes and let us know.

**Comment by casjone** [comment]
Thank you! This definitely got me closer. 

 

From: Evan Thoms ***@***.***> 
Sent: Wednesday, September 7, 2022 5:06 PM
To: usgs/gems-tools-pro ***@***.***>
Cc: Jones, Casey ***@***.***>; Author ***@***.***>
Subject: [External] Re: [usgs/gems-tools-pro] NON-UNIQUE VALUE OF LABEL:
Silt (Issue #33)

 

	
You don't often get email from ***@***.***
***@***.***> . Learn why this is important
<https://aka.ms/LearnAboutSenderIdentification> 

	

This message was sent from a non-IU address. Please exercise caution when
clicking links or opening attachments from external sources.

 

It all comes down to formatting. Each unit needs to have a map unit label,
name, age, and description as below
<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.co
m%2Fusgs%2Fgems-tools-pro%2Fwiki%2FCMU-and-DMU&data=05%7C01%7Ccasjone%40iu.e
du%7C6896c3107442413441b608da9114ffb5%7C1113be34aed14d00ab4bcdd02510be91%7C0
%7C0%7C637981816623599120%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIj
oiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=jJSPEKezhv6S6
JmCBWTG3JblvoOgmyIITTQospD20tQ%3D&reserved=0> , and all separated by the
appropriate spaces, em-dashes, parantheses, and have no paranthetical
breaks.

 
<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-imag
es.githubusercontent.com%2F5376315%2F188977527-af5db1aa-a8a3-4ef8-84dc-aef17
a91f31b.png&data=05%7C01%7Ccasjone%40iu.edu%7C6896c3107442413441b608da9114ff
b5%7C1113be34aed14d00ab4bcdd02510be91%7C0%7C0%7C637981816623599120%7CUnknown
%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6M
n0%3D%7C3000%7C%7C%7C&sdata=WCDBB35bHfxWcIFgVC7GtGQwZK5nty5bynFLXqEWX%2FM%3D
&reserved=0> 

testPamphletDmu is closer to working than testPamphletDmu2 (where 'Silt,',
because it starts a paragraph, is parsed out as a map unit label) but
MARTINSVILLE FORMATION (HOLOCENE) needs to be re-styled as Heading3 and you
need to add (ages) after all of the unit names. In places where (undivided)
follows the name instead of, or in addition to, an age, move that to just
after the name separated by a comma

 
<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-imag
es.githubusercontent.com%2F5376315%2F188979128-b566b15d-8499-4178-a8d7-7248a
184d636.png&data=05%7C01%7Ccasjone%40iu.edu%7C6896c3107442413441b608da9114ff
b5%7C1113be34aed14d00ab4bcdd02510be91%7C0%7C0%7C637981816623599120%7CUnknown
%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6M
n0%3D%7C3000%7C%7C%7C&sdata=Vv1jLoGfvk3RfRAQxUS3c%2BTWuB%2FA3XcWac6BvpDQVNE%
3D&reserved=0> 

Try those changes and let us know.

-
Reply to this email directly, view it on GitHub
<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.co
m%2Fusgs%2Fgems-tools-pro%2Fissues%2F33%23issuecomment-1239882348&data=05%7C
01%7Ccasjone%40iu.edu%7C6896c3107442413441b608da9114ffb5%7C1113be34aed14d00a
b4bcdd02510be91%7C0%7C0%7C637981816623599120%7CUnknown%7CTWFpbGZsb3d8eyJWIjo
iMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&
sdata=rKx2%2Fv3%2FHYaom%2BkCmFU0p5%2FLXeyrjw9VF2FmQ3ZhbiE%3D&reserved=0> ,
or unsubscribe
<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.co
m%2Fnotifications%2Funsubscribe-auth%2FA2EF5IVKZ6HVTKNZPKLYBCLV5D7UZANCNFSM6
AAAAAAQGZNGVE&data=05%7C01%7Ccasjone%40iu.edu%7C6896c3107442413441b608da9114
ffb5%7C1113be34aed14d00ab4bcdd02510be91%7C0%7C0%7C637981816623599120%7CUnkno
wn%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI
6Mn0%3D%7C3000%7C%7C%7C&sdata=91YX4GKq9fUATyxGiUdO75488GB%2FS95j7XjarlIfa5k%
3D&reserved=0> .
You are receiving this because you authored the thread.
<https://github.com/notifications/beacon/A2EF5ISOO6NK7PAHBZ3MOD3V5D7UZA5CNFS
M6AAAAAAQGZNGVGWGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTS
J44NGY.gif> Message ID: ***@***.***
***@***.***> >

**Comment by casjone** [comment]
thank you; that definitely got me closer. i found another issue. i was using em-dashes (—) using the alt code: 'alt+0151'. i switched it to two dashes and that works to parse out the description.

**Comment by ethoms-usgs** [comment]
No traffic in a long time. Closing
