### ISSUE TITLE
Build Metadata Tool Fails When Using Custom Definitions and Does not Apply Custom Attributes

### ISSUE THREAD

**Issue by dmiranda204** [DOI-USGS/gems-tools-pro#40]
There are actually two parts to this issue: related to the Build Metadata tool:

1. I receive an error when specifying a custom definition file. 
2. After applying what I think is the fix, the custom attributes were not being added to the metadata file.

**Part 1:**
When running the Build Metadata tool, and specifying a properly completed custom definition file, I receive the following error:
![image](https://user-images.githubusercontent.com/119333158/214409747-08f77ed0-545a-4199-a8e9-1a34bbebd7de.png)
I think the issue is in the if-else statement starting on line 579. myEntityDict is not defined if a custom definition file is specified (it is only defined if a custom file is _not used_.) Right before the else statement, I think we need to set the variable to the custom definitions myEntityDict:
`myEntityDict = myDef.myEntityDict`

**Part 2:**
I made the change on a local copy of the script. The tool then ran, but was not applying the attributes from myAttribDict. I think in this case, it's line 353. 
Currently, it reads: `res = [key for key in gDef.myAttribDict if field.endswith(key)]`.

However, I think it should be: `res = [key for key in myDef.myAttribDict if field.endswith(key)]`.

Note myDef instead of gDef. After applying this change, the tool appears to operate correctly.

I do not have myself setup to do pull requests, so I hope this gives you enough information to go on.

**Comment by ethoms-usgs** [comment]
Wow! A new issue WITH fixes. Can't get better than that. 

I found the same errors you did and with the fixes saw that custom attributes were properly filled out. Didn't do robust testing, but I think we're good. I pushed a new version and will close this.

Thanks, Dan!
