### ISSUE TITLE
Cross section tool fails if options in Extras section are checked.

### ISSUE THREAD

**Issue by tfelger** [DOI-USGS/gems-tools-pro#41]
I am trying to run the Project Map Data to Cross Section tool and having some issues. I downloaded a new version of the toolbox and tried the tool in it and it failed. I looked thru the issues and saw that the tool is being worked on in a separate branch, so I downloaded that toolbox. I can get it to run once as long as I don't check any options in the Extras section. As soon as I do that it crashes with the following error message (note that it says my version is obsolete, even tho it's the most recent one, as far as I can tell). 

![image](https://user-images.githubusercontent.com/52179206/216140046-4a74e5d1-c5a8-46f0-976e-ed24f1d72f1b.png)

My input parameters are: 
![image](https://user-images.githubusercontent.com/52179206/216140139-31d38687-00e8-4644-b95b-8c159996fb55.png)

I've tried only checking Add Surface Profile or Add frame, and both fail. I've also not been able to rerun the tool twice in one session. I have to run it, close and reopen Pro, and run it again.

Let me know if you have more questions. I'm runing Pro 3.

Thanks!

-tracey

**Comment by tfelger** [comment]
I looked more closely at the snapshots from the posts in June and July, and tried to mimic them as much as possible. I've gotten it to work successfully 3 times in a row with all the options I want, soo I you can ignore my previous post on this issue!

**Comment by ethoms-usgs** [comment]
I got the error about the parameter not being a feature class and tracked it down to an existing feature class not being deleted before running a second time. I think it's fixed now. I will close this issue.
