### ISSUE TITLE
Cross section tool - ApparentDip, Obliquity, and PlotAzimuth fields not added to OrientationPts

### ISSUE THREAD

**Issue by tfelger** [DOI-USGS/gems-tools-pro#42]
The tool help says that fields ApparentDip, Obliquity, and PlotAzimuth will be added to point feaature classes that have fields Azimuth and Inclination, but they are not. Here is a snapshot of the fields in the output OrientationPts feature class.

![image](https://user-images.githubusercontent.com/52179206/216183164-02ea8de9-cbec-4a98-8f9b-03609a8dc63f.png)

Would be great to have addtional fields. Thanks!

-t

**Comment by ethoms-usgs** [comment]
Try again, Tracey.
I got the same errors you did and then it ran correctly after some edits.

https://github.com/DOI-USGS/gems-tools-pro/tree/xs-update

**Comment by tfelger** [comment]
Thanks Evan! I tried again, and now it has fields ApparentDip, Obliquity, and MapAzimuth. Obliquity isn't populated, but I'm not sure how important that is? And I'm assuming that MapAzimuth is what you are referring to as PlotAzimuth, in the tool help - the field that is the rotation field for symbolization?

**Comment by ethoms-usgs** [comment]
Sorry about that! Obliquity should get written there now, but, yes, it's not that important. 
Actually Azimuth, in the projected fc, is what you want. MapAzimuth is the same as strike in your map-view points. 
I think I will change that to PlotAzimuth to follow the help.

**Comment by tfelger** [comment]
Hi Evan, it works now. Thanks for the clarification of the fields. It is confusing (to me, anyway!), to have Azimuth populated with the apparent dip angle that the symbol should be rotated on in the cross section, since it is the field that stores the measured azimuth in the map OrientationPts. If it's not too hard to preserve the orginal azimuth in Azimuth, and write the new value into PlotAzimuth (or some such) field, I think that would make things clearer for the user.

Thanks for working on this - it looks like this tool is really coming together nicely!
