### ISSUE TITLE
New Validation Tool

### ISSUE THREAD

**Issue by kalexanderUSGS** [DOI-USGS/gems-tools-pro#48]
I tried out your new validation script, and it flagged a couple things incorrectly 

1. We have a field 'OrigMapUnit' that has map units that we are not defining in our DMU, the correct values are in the 'MapUnit' field. The tool flagged every entry in the 'OrigMapUnit' as not in the DMU
2. We have an additional table that has digitization Methods listed and it flagged our methods as not being defined in the glossary
3. I think its telling me that im missing my GeologicMap dataset, but im not sure how I would be missing it if it went through and checked it. 

Also the old 2.9.4 validation script adds the GeoMaterialDict to the database and the new 2.10.2 validate tool does not, and in the new validate tool I think there is a typo in the geomat. dict for "Made" deposits

**Comment by ethoms-usgs** [comment]
Undefined methods found in a non-GeMS table should now get logged as warnings, not errors. I haven't addressed fields like OrigMapUnit yet.

**Comment by ethoms-usgs** [comment]
I have changed the tool so that undefined values in fields like OrigMapUnit are logged as warnings, not errors.  Try it out and let me know.

**Comment by ethoms-usgs** [comment]
Fixed
