### ISSUE TITLE
Build Metadata tool

### ISSUE THREAD

**Issue by sjohnstone-usgs** [DOI-USGS/gems-tools-pro#49]
Two minor issues:

1) In the ScriptTool GUI for 'Build Metadata', it looks like the full list of values in the 'Sources', 'History', and 'Missing definitions...' arguments were not input (so Arc recognizes valid options in the code as errors). 

2) As noted in the [documentation](https://github.com/DOI-USGS/gems-tools-pro/wiki/GeMS-Tools-Documentation#build-metadata), the fact that Arc doesn't set the PROJ_LIB environmental path can cause issues w/ the projection function.  Rather than try and redefine this absolute environmental path at the system level (which I worried would upset other environments), I just added the following to near the top of my 'GEMS_MetadataFGDC_AGP2.py' file (must be somewhere below 'import arcpy' line): 

** edited to try and get code to format in markdown

```
  #In some ArcPro created virtual environments the path to the PROJ library (opensource projections) is not always created 
  #This will cause a gdal/osr error when trying to transform coordinates to a new CRS.
  #This statement attempts to guess what the path should be
  #though there is no guarantee this will work w/ all environments

  import os
  
  if not('PROJ_LIB' in os.environ):
      arcpy.AddMessage('Could not find PROJ_LIB in environment path, trying to guess path to proj.db folder')
      proj_path = r'C:\ArcGIS\Pro\Resources\pedata\gdaldata' #You could specify this as an optional argument (w/ a default path)
      projdb_path = os.path.join(proj_path,'proj.db')
      if os.path.exists(projdb_path):
          arcpy.AddMessage('Found proj.db in expected directory, adding to working environmental variables')
          os.environ['PROJ_LIB'] = proj_path
      else:
          #Splitting warning message into multiple lines for issue format
          warningMessage = 'Could not find proj.db in expected directory: {} \n'.format(proj_path)
          warningMessage += 'Code expected to fail dur to an error in CoordinateTransformation_TransformPoint. \n'
          warningMessage += 'Please identify the correct location of proj.db'
          arcpy.AddWarning(warningMessage)
```

**Comment by ethoms-usgs** [comment]
1. I have seen value lists stored in the parameter form be flakey like this elsewhere, getting overwritten when it's not clear why. I will reset them.
2. that's a good idea. Thanks for working it up. I will try it out.

**Comment by ethoms-usgs** [comment]
Actually, I'd forgotten, some of those value list options are set in the validation class of the tool depending on other inputs. They work for me in that the list values change as I set and reset the dependent parameters. Do you have some parameter values that produce an error message?

**Comment by sjohnstone-usgs** [comment]
Apologies Evan!  I had just checked the value list in the parameters tab after clicking through the options (with no inputs specified). When I actually specify input parameters the validations are working correctly and I can see the suite of value options. 

Thanks for the quick response! I'll mark this as fixed.
