### ISSUE TITLE
Syntax error, integer type in Project Map Data to Cross Section tool

### ISSUE THREAD

**Issue by LLeBlanc110** [DOI-USGS/gems-tools-pro#61]
I ran the tool on a fully attributed gems gdb and this is the message returned - 

![image](https://github.com/DOI-USGS/gems-tools-pro/assets/61474179/93dcceee-c7e2-4fe1-a45f-b8df3e005bfa)

![image](https://github.com/DOI-USGS/gems-tools-pro/assets/61474179/cca59145-6941-413d-a78a-734ec79c4fec)

There's only one cross section line in the CartographicLines feature class. There's already a feature dataset 'CrossSectionB' in the gdb from when I as messing around with the tool in ArcMap a couple years ago, does that mattter? Another question, the Pro tool specifies a "GeMS style geodatabase," _how_ GeMS compliant does it need to be and do the attribute fields all need to be filled-in for the tool to work? I asked one of our mappers to run it on their gdb and they received the same error. I've attached the gdb that I ran the tool on, thanks for your help.

[EulatonGeMSxsect.gdb.zip](https://github.com/DOI-USGS/gems-tools-pro/files/11817964/EulatonGeMSxsect.gdb.zip)

**Comment by ethoms-usgs** [comment]
Hi Lainey,
Try the cross section tool on the xs-update branch - DOI-USGS/gems-tools-pro at xs-update (github.com)<https://github.com/DOI-USGS/gems-tools-pro/tree/xs-update>
Download from the green Code button, not the latest release.
Please let me know how it goes. Once I get enough reports that it is working ok, I will merge it into the main toolbox.

--
​​Evan Thoms
US Geological Survey, Alaska Science Center
4210 University Drive, Anchorage, AK 99508

________________________________
From: Lainey L ***@***.***>
Sent: Wednesday, June 21, 2023 11:11 AM
To: DOI-USGS/gems-tools-pro ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] [DOI-USGS/gems-tools-pro] Syntax error, integer type in Project Map Data to Cross Section tool (Issue #61)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



I ran the tool on a fully attributed gems gdb and this is the message returned -

[image]<https://user-images.githubusercontent.com/61474179/247649138-93dcceee-c7e2-4fe1-a45f-b8df3e005bfa.png>

[image]<https://user-images.githubusercontent.com/61474179/247291158-cca59145-6941-413d-a78a-734ec79c4fec.png>

There's only one cross section line in the CartographicLines feature class. There's already a feature dataset 'CrossSectionB' in the gdb from when I as messing around with the tool in ArcMap a couple years ago, does that mattter? Another question, the Pro tool specifies a "GeMS style geodatabase," how GeMS compliant does it need to be and do the attribute fields all need to be filled-in for the tool to work? I asked one of our mappers to run it on their gdb and they received the same error. I've attached the gdb that I ran the tool on, thanks for your help.

EulatonGeMSxsect.gdb.zip<https://github.com/DOI-USGS/gems-tools-pro/files/11817964/EulatonGeMSxsect.gdb.zip>

**Comment by LLeBlanc110** [comment]
@ethoms-usgs The tool runs, but it doesn't generate any spatial data, even when the 'Add surface profile' and 'Add frame' is checked, is that right? I ran with the token "eulaton2" without the surface profile and frame checked and it just generated tables, I ran again with "eulaton3" with those extras checked and it only generated tables again. And, the MapUnitPolys events table doesn't generate with the token.

I'm more familiar with the ArcMap version and pre-GeMS tools you built, so maybe I'm assuming this tool generates data that it actually isn't meant too...

![image](https://github.com/DOI-USGS/gems-tools-pro/assets/61474179/85bde5d0-ac83-4fef-b2d1-89be1cccaa12)
![image](https://github.com/DOI-USGS/gems-tools-pro/assets/61474179/3f62a3c2-e213-47cd-b59d-2d7b93907b45)
![image](https://github.com/DOI-USGS/gems-tools-pro/assets/61474179/74623780-df0c-460c-a420-942eafb74e41)

**Comment by ethoms-usgs** [comment]
Set the scratch workspace to something other than where you want the feature classes to end up. The tool needs a place to write intermediate datasets to and defaults to your default.gdb. Unless you check 'save intermediate data', the intermediate and final feature classes are deleted (I forgot to add code to track down the _evtbl tables) so if the input and scratch workspaces are the same, you end up with no feature classes. 

I put that option on the parameter form for troubleshooting but I should probably remove it and just tell people to look in the default.gdb.

**Comment by LLeBlanc110** [comment]
Ah ok, makes sense. I changed the workspace and everything ran as it should. Thanks!

**Comment by ethoms-usgs** [comment]
Great!
