### ISSUE TITLE
v2.11.2 Validate Database error

### ISSUE THREAD

**Issue by LLeBlanc110** [DOI-USGS/gems-tools-pro#69]
Ran the tool with "Compact GDB" and everything else unchecked and received the following error - 

![image](https://github.com/DOI-USGS/gems-tools-pro/assets/61474179/fe89c758-d5df-46a4-9357-f42da29aaf56)

in text - 

Validate Database
=====================
Parameters

Input geodatabase or geopackage     C:\Users\EBollen\Documents\ArcGIS\Projects\FlagMountain\FlagMountain_EMRI21.gdb
Output workspace     C:\Users\EBollen\Documents\ArcGIS\Projects\FlagMountain\Validation
Validate standalone file     
Validate embedded metadata     
Report errors with _ID, not OBJECTID     false
Skip topology checks     false
Refresh GeoMaterialDict     false
Delete unused Glossary and DataSources rows     false
Compact GDB     false
Open report when done     true
=====================
Messages

Start Time: Monday, August 28, 2023 1:51:43 PM
This version of the tool is up to date
Metadata not checked. File needs to be in XML format.
Traceback (most recent call last):
  File "C:\Users\EBollen\Documents\ArcGIS\gems-tools-pro-2.11.2\Scripts\GeMS_ValidateDatabase.py", line 1549, in <module>
    rule2_1_results = rule2_1(db_dict, is_gpkg)
  File "C:\Users\EBollen\Documents\ArcGIS\gems-tools-pro-2.11.2\Scripts\GeMS_ValidateDatabase.py", line 1204, in main
    database dictionary. If blank, it is an extension"""
AttributeError: module 'GeMS_utilityFunctions' has no attribute 'eval_bool'

Failed script Validate Database...
Failed to execute (ValidateDatabase).
Failed at Monday, August 28, 2023 1:51:45 PM (Elapsed Time: 1.70 seconds)

**Comment by ethoms-usgs** [comment]
I have seen this error a couple times now with the new version of the tool which includes some edits to GeMS_utilityFunctions. It's like the new file is not getting found by Pro; it goes looking for the older version. Try closing Pro and either deleting the older toolbox folder or, when you download v 2.11.2, put it in a different folder and try to access the tool there. And, in Pro, access the tool from the Catalog pane, not by going to geoprocessing history and running a saved entry. I don't know for sure that's important, but it should guarantee that Pro is not running any cached files.

**Comment by LLeBlanc110** [comment]
That fixed it, thanks!
