### ISSUE TITLE
Validate Database - GeoMaterialDict does Not Meet Standard

### ISSUE THREAD

**Issue by dmirandaUSGS** [DOI-USGS/gems-tools-pro#78]
While working to convert a database to GeMS, Tracey Felger and I were getting a validation error when using Validate Database on the GeoMaterialsDict. See below:
![image](https://github.com/DOI-USGS/gems-tools-pro/assets/119333158/695787fb-b165-44d5-a21a-6368b6f0d3f0)

The GeMS database we used was generated with the Create New Database script, so I would expect the GeoMaterialsDict to be correct.

To troubleshoot the problem, I:

1. Pulled the latest version of the toolbox
2. Ran Create New Database
3. Validated the brand new empty GeMS database

I ended up receiving the same error about definitions missing for the three GeoMaterialDict items. I took a look at the GeMS_lib.gdb, where the table is copied from in the Create New Database script, and noticed that the GeoMaterialDict table is missing those three definitions:
![image](https://github.com/DOI-USGS/gems-tools-pro/assets/119333158/0540c7a5-0284-4146-86c6-44a45b4b0bcc)

Should the GeMS_lib.gdb/GeoMaterialsDict table have defintions for Other materials, Water or ice, and Unmapped area so that we can prevent this validation error?

**Comment by ethoms-usgs** [comment]
Ok, hang on. I need to change the Create Database tool. That tool does make the table from GeMS_lib.gdb, but the Validate Database uses GeoMaterialDict.csv in the Scripts folder. I like saving the table in the more open format so I will work toward removing GeMS_lib.gdb.

**Comment by ethoms-usgs** [comment]
Updated in v2.12.4
