### ISSUE TITLE
Tool not Finding MapUnitPolys?

### ISSUE THREAD

**Issue by LeahZaitlin** [DOI-USGS/gems-tools-pro#88]
When I run the newest version of the Validate database tool, the tool seems to run ok, but then when I look at the output it seems to have not registered MapUnitPolys, and so gives a topology error in the check.  I tried to run the same database with an older version of GeMS and its giving me level 3 compliance for this same database, so I am not sure why the new version is not registering the MapUnitPolys.  I tried opening the same database in a new project, and opening a new project from a copy of the database, but its giving me the same issue.  Any idea why this is happening and how to fix it?

![image](https://github.com/DOI-USGS/gems-tools-pro/assets/113056776/9846bc58-d104-4059-9102-da89bbae79f9)

These are the messages I am getting when the tool runs: 
Validate Database
=====================
Parameters

Input geodatabase or geopackage     C:\Users\lzaitlin\Desktop\Wickenburg.gdb
Output workspace     C:\Users\lzaitlin\Desktop\WGEMSTESTs\GEMS2
Validate standalone file     
Validate embedded metadata     
Report errors with _ID, not OBJECTID     false
Skip topology checks     false
Refresh GeoMaterialDict     false
Delete unused Glossary and DataSources rows     false
Compact GDB     true
Open report when done     true
=====================
Messages

Start Time: Thursday, November 16, 2023 10:15:17 AM
This version of the tool is up to date: GeMS_ValidateDatabase.py, version of 10/18/2023
​
Looking at level 2 compliance
Rule 2.1 - Has required elements: nonspatial tables DataSources, 
        DescriptionOfMapUnits, GeoMaterialDict; feature dataset GeologicMap with 
        feature classes ContactsAndFaults and MapUnitPolys
Rule 2.2 - Required fields within required elements are present and correctly defined
2.3 All MapUnitPolys and ContactsAndFaults based feature classes obey Level 2 topology rules: 
        no internal gaps or overlaps in MapUnitPolys, boundaries of MapUnitPolys are covered by ContactsAndFaults
	Topology in GeologicMap found
		Looking at validation results for errors
2.4 All map units in MapUnitPolys have entries in DescriptionOfMapUnits table
2.5 No duplicate MapUnit values in DescriptionOfMapUnits table
2.6 Certain field values within required elements have entries in Glossary table
2.7 No duplicate Term values in Glossary table
2.8 All xxxSourceID values in required elements have entries in DataSources table
2.9 No duplicate DataSources_ID values in DataSources table
​
Looking at level 3 compliance
3.1 Table and field definitions conform to GeMS schema
3.2 All MapUnitPolys and ContactsAndFaults based feature classes obey Level 3 topology rules: 
        no overlaps, self-overlaps, or self-intersections in ContactsAndFaults.
3.3 No missing required values
3.4 No missing terms in Glossary
3.5 No unnecessary terms in Glossary
3.6 No missing sources in DataSources
3.7 No unnecessary sources in DataSources
3.8 No map units without entries in DescriptionOfMapUnits
3.9 No unnecessary map units in DescriptionOfMapUnits
3.10 HierarchyKey values in DescriptionOfMapUnits are unique and well formed
3.11 All values of GeoMaterial are defined in GeoMaterialDict. GeoMaterialDict is as specified in the GeMS standard
3.12 No duplicate _ID values
3.13 No zero-length or whitespace-only strings
Check Metadata option was skipped
​
Inventorying database:
	Looking for extensions to GeMS schema
	Finding occurrences of map units
	Storing contents of non-spatial tables
	Building database inventory
DONE
Succeeded at Thursday, November 16, 2023 10:15:41 AM (Elapsed Time: 24.31 seconds)

**Comment by ethoms-usgs** [comment]
Could you post a screenshot from Catalog of the contents of the gdb?

**Comment by LeahZaitlin** [comment]
![image](https://github.com/DOI-USGS/gems-tools-pro/assets/113056776/26e889b8-2647-4756-8090-6a1456461b42)

Yes, here is what the gdb looks like

**Comment by ethoms-usgs** [comment]
Ah, ok, Does your GeologicMap_Topology have MapUnitPolys in it, or just ContactsAndFaults? I changed the tool to check a producer-made topology relationship if it was present because making one from scratch and validating can take a long time.

**Comment by LeahZaitlin** [comment]
![image](https://github.com/DOI-USGS/gems-tools-pro/assets/113056776/053502f3-9711-4f3b-98e9-ab269c6ceb4e)

Our topology errors does not have a mapunitpolys layer, but it does check polygon errors?

**Comment by ethoms-usgs** [comment]
I think there is always a placeholder for Polygon Errors even when there are no polygon feature classes. 

I am getting reports of other people using simplified topologies for error checking of lines only so we should rethink the way the new tool works. In the meantime, your workarounds would be to either add MapUnitPolys and the appropriate rules to your topology or delete it. And, of course, Skip Topology until you are ready to finalize the gdb.

**Comment by LeahZaitlin** [comment]
Ok, I tried deleting it and now its running properly and giving me GeMS3,  so that seems to be a good workaround for now, since we werent putting anything in there for this map.  Thank you for your help with this!

**Comment by ethoms-usgs** [comment]
Great! Good to hear. I will close this issue.
